### PR TITLE
Make underlines and strikethroughs respect align

### LINKED ISSUE #141: Underline alignment regression
cc @trimental

Just noticed that the PR to add alignment for tables regressed alignment for text vs its underline

**Repro**

```html
<h1 align="center">Some text</p>
```

**Rendered**

image

You can see that the text is center aligned while the underline is left aligned

This seems to be due to removing the alignment from the `Key` which was used to set the alignment of the `buffer_line`. Admittedly I'm not really familiar enough with the renderer to know how to fix things without likely regressing other parts

### PR DESCRIPTION
**Pull request by CosmicHorrorDev**
Resolves #141 

@Valentin271 I got a better idea of the underline code after working on #225. The fix _feels_ hacky, but I'm not really familiar with the renderer and there's a lot of messy code in there to begin with :shrug:

From what I can gather `left` gets set to the x coord of the text area including the `Align`

## Demo

(Includes the use of `--page-width` to check that too)

https://github.com/trimental/inlyne/assets/30302768/107b09f1-e6f4-490e-9484-b259fb3fde88

### CODE REVIEW

File: src/text.rs [hunk 1]
```diff
@@ -372,7 +377,7 @@ impl TextBox {
                 let start_cursor = Cursor::new(line.line_i, range.start);
                 let end_cursor = Cursor::new(line.line_i, range.end);
                 if let Some((highlight_x, highlight_w)) = line.highlight(start_cursor, end_cursor) {
-                    let x = screen_position.0 + highlight_x;
+                    let x = left + highlight_x;
```
Comment (CosmicHorrorDev) [inline src/text.rs:380]: `left` is already `screen_position.0` for `Align::Left`, but correctly handles the offset for `Center` and `Right` as well (this is why the underlines were stuck left-aligned)

**Review by Valentin271 — COMMENTED** [review]
> there's a lot of messy code in there to begin with

Yep felt that too.

This does feel a bit hacky to me too. Ideally `render_lines` would take a `CachedTextArea` or similar and not every detail about it.
But still this is way better than what I was trying to do on my fork.

**Comment by CosmicHorrorDev** [comment]
> This does feel a bit hacky to me too. Ideally `render_lines` would take a `CachedTextArea` or similar and not every detail about it.

Good point! Done and done

**Review by Valentin271 — APPROVED** [review]
Looks good to me
